version: "2"

linters:
  enable:
    - errcheck
    - govet
    - gosimple
    - ineffassign
    - staticcheck
    - unused
    - misspell

linters-settings:
  misspell:
    locale: US
  errcheck:
    exclude-functions:
      - (*github.com/spf13/cobra.Command).MarkFlagRequired

issues:
  exclude-dirs:
    - vendor
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
